MAX_TOTAL_TOOL_CALLS = 30
MAX_SEARCH_CALLS = 5
MAX_OPEN_URL_CALLS = 10

MAX_SNIPPET_LENGTH = 150
MAX_SEARCH_RESULTS_KEPT = 5
MAX_FORMATTED_RESULTS_LENGTH = 2000

MAX_MEMORY_LIMIT = 200
MEMORY_DB_PATH = "memories.db"

# 新增
MAX_FILE_LIMIT = 200
FILE_ROOT_DIR = "agent_workspace"